version: '3.9'
services:
  api:
    build:
      # context: ./api-test
      context: ./API
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api
    hostname: api.localhost
    ports:
      - "8000:8000"
    networks:
      - lms-network

  lms-app:
    build:
      context: ./lms-app
      dockerfile: Dockerfile
    container_name: lms-app
    hostname: app.localhost
    depends_on:
      - api
    volumes:
      - ./lms-app/:/lms-app
      - /lms-app/node_modules
      - /lms-app/.next
    ports:
      - "3001:3001"
    networks:
      - lms-network

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    container_name: landing
    volumes:
      - ./landing/:/landing
      - /landing/node_modules
      - /landing/.next
    ports:
      - "3000:3000"
    networks:
      - lms-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /nginx/default.conf
      - /nginx/nginx.conf
    depends_on:
      - api
      - lms-app
      - landing
    ports:
      - "80:80"
    networks:
      - lms-network

networks:
  lms-network:
