version: '3.9'
services:
  api:
    build:
      context: ./api-test
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - lms-network

  lms-app:
    build:
      context: ./lms-app
    container_name: lms-app
    ports:
      - "3001:3001"
    depends_on:
      - api
    # volumes:
      # - /lms-app/node_modules
      # - ./lms-app/pages:/lms-app/pages
      # - ./lms-app/public:/lms-app/public
      # - ./lms-app.styles:/lms-app/styles
      # - ./lms-app/next.config.js:/lms-app/next.config.js
      # - ./lms-app/tailwind.config.js:/lms-app/tailwind.config.js
    command: npm run dev
    networks:
      - lms-network

  landing:
    build:
      context: ./landing
    container_name: landing
    # expose:
    #   - 3000
    ports:
      - "3000:3000"
    networks:
      - lms-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - lms-app
      - landing
    networks:
      - lms-network

networks:
  lms-network: