# Generated by Django 3.2.8 on 2023-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
