# Generated by Django 3.2.8 on 2023-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab_manager',
            field=models.BooleanField(default=False),
        ),
    ]
