# Generated by Django 3.2.8 on 2023-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20230504_2248"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="manufacturer",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="machine",
            name="model_number",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="machine",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
