# Generated by Django 3.2.8 on 2023-05-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230507_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='time_takes',
            new_name='duration',
        ),
    ]
