name: CIDCNext

 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm ci, build and test
        working-directory: lms-app
        run: |
          npm ci
  
      - name: Run Jest
      working-directory: lms-app
      run: npm test
      

      - name: Run Linting
        working-directory: lms-app
        run: npm run lint
            
