name: CIDCNext
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm ci
        working-directory: lms-app
        run: |
          npm ci
          
      - name: Run Jest
        working-directory: lms-app
        run: npm run test:ci
    
      - name: Run Linting
        working-directory: lms-app
        run: npm run lint
            
